# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newname', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('QQ_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
